### ISSUE TITLE
NadiaVM interprets invalid move commands as moving player east

### ISSUE THREAD

**Issue by alicerunsonfedora** [UnscriptedVN/fira#2]
From UnscriptedVN/game#29:

> given invalid command (including simply pressing enter), all moves henceforth will only move east. For example, "move player west" would move east.

This is caused by supplying "east" when an invalid command occurs: https://github.com/UnscriptedVN/fira/blob/e6197e4297c837eea715fa78ce55e9e182a6437f/uvn_fira/core/vm.py#L322

This should not be the case. An "other" option should be specified when the player supplies an invalid move command with a blank tuple `(0, 0)`.

**Comment by andy-k** [comment]
the identified line may not be the only cause for the bug.

"move player west" is valid; it's just misinterpreted as "move player east" once an invalid command happens.
- the invalid command need not be a move command. it can be any typo, or even an empty string.
- once the minigame processes an invalid command, for the remainder of the minigame, all move commands move east, this includes valid "move player west"/"move player north"/"move player south".
